version: "3.9"

services:
  weather_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_api
    ports:
      - "8000:8000"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    networks:
      - weather_net

  weather_dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_dashboard
    ports:
      - "8501:8501"
    command: streamlit run src/dashboard/dashboard.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - weather_api
    networks:
      - weather_net

  weather_tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_tests
    depends_on:
      - weather_api
    networks:
      - weather_net
    entrypoint: >
      sh -c "
        echo 'Attente du démarrage de l’API...';
        until curl -s http://weather_api:8000/current/Paris; do
          sleep 1;
        done;
        echo 'API prête. Lancement des tests...';
        pytest src/tests
      "

networks:
  weather_net:
    driver: bridge
